### ISSUE TITLE
MAVlink encryption

### ISSUE THREAD

**Issue by azaallouch** [MarkSei/thesis#1]
I'm trying to encrypt mavlink packet, how can I see the original text and the encrypted text.

**Comment by MarkSei** [comment]
Hey azaallouch,

First of all, thank you for your interest in my project. Before I try to answer your question I should warn you. This mainly serves as a proof of concept, to see what could be gained from implementing these cryptographic primitives performance-wise. IT IS IMPORTANT to note that this **is in no way** a complete implementation. The key-exchange is limited and it is using a possibly bad choice of parameters. There is a few bugs in the decryption that I experienced on certain systems. If you plan to use this for bigger applications you should thoroughly test it. I won't have the time for a while to finish building it. 

Now for the answer: All you need to do, is to write your message to a buffer, and then print it as you would any other array. Something like 

```
uint8_t buf[BUFSIZE];
mavlink_message_t msg;

uint16_t len = 0;
len = mavlink_msg_to_send_buffer(buf, &msg);
for (unsigned int i = 0; i < len; ++i) {
    printf("%02x", buf[i]);
}
```

This prints the encrypted message. The encryption happens when the message is finalized, so to print the original text, you have to print the content of the encapsulated message, and not the generated one.

**Comment by azaallouch** [comment]
thanks for your reply,
i have modified mavlink_helpers.h to add encryption.
In your code you have doing aes_encrypt under the **MAVLINK_HELPER uint16_t mavlink_finalize_message_buffer(mavlink_message_t* msg, uint8_t system_id, uint8_t component_id,						      mavlink_status_t* status, uint8_t min_length, uint8_t length, uint8_t crc_extra)**.
After aes_encrypt((uint8_t*)_MAV_PAYLOAD(msg), msg->len, status->signing->key_send_enc, nonce);

 i write for (unsigned int i = 0; i < msg->len; ++i) {
    printf("%02x", _MAV_PAYLOAD(msg)[i]);
}
nothing is printed on the console, but in my code i used aes_encryption  under the MAVLINK_HELPER void _mav_finalize_message_chan_send(mavlink_channel_t chan, uint32_t msgid,
                                                    const char *packet, 
						    uint8_t min_length, uint8_t length, uint8_t crc_extra) 
this generate this  
![image](https://user-images.githubusercontent.com/38465623/39154397-e8c94dde-4745-11e8-8b22-ed9eb80dae93.png)

you see when using aes cbc encryption the cyphertext length is different from the original text size,
what i want to do is to send this encrypeted text to a server. 
My problem is in the   	_mavlink_send_uart(chan,packet, length); the packet parameter is the original text so i must change it with cyphertext variable in my case packet2 and the length must be changed by the cyphertext length, when i encrypted text with the originaltext length the udp server receive  the packet, but when i use send uart with the cyphertext length the server does not accept any thing.

Cloud help me to solve this issue

**Comment by MarkSei** [comment]
I suspect there might be a number of things missing here. I don't see any padding field in your generated messages. Have you used the default mavgenerate.py or my "parser.py" to generate your libraries? It's important that you use mine, as CBC mode requires the padding added by that custom parser. 

This is also why the ciphertext is longer than the plaintext. You can only encrypt multiples of the blocksize in CBC. When using my parser.py the original message will have the correct value in the length field with padding added.

**Comment by azaallouch** [comment]
No, i haven't use mavgenerate.py nor "parser.py.
the padding is clear, here in my example the original msg length is 28 not multiple of 16byte, and the generated cipher text length is 32 multiple of 32.
why should i use  mavgenerate.py or my "parser.py.
Can you explain more?

**Comment by MarkSei** [comment]
Do not use mavgenerate. Use parser.py. I added that to ensure a padding field would be added to each message definition before the library was generated. It would add a new field to each message you define with the number of bytes needed to reach a multiple of 16.

It is not really a sophisticated script so you should be able to look at it and see how to use it. When you have used it, you will have all the message headers you already have, but each one with a constant zero padding array.

**Comment by azaallouch** [comment]
Thanks MarkSei for you help,
So i will use your code cbcmav2 and parser.py.

**Comment by MarkSei** [comment]
You are welcome, and again please be mindful about using this. I really can't stress it enough: There's been almost no testing of the code
